//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleCodeCompletion {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleCodeCompletion.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;SyntaxDefinition name=&quot;C#&quot;
        ///        xmlns=&quot;http://icsharpcode.net/sharpdevelop/syntaxdefinition/2008&quot;&gt;
        ///	&lt;Color name=&quot;Method&quot; foreground=&quot;#8b531f&quot; /&gt;
        ///	&lt;Color name=&quot;Class&quot; foreground=&quot;#2b91af&quot; /&gt;
        ///	&lt;Color name=&quot;Type&quot; foreground=&quot;Blue&quot; /&gt;
        ///	&lt;Color name=&quot;Return&quot; foreground=&quot;Blue&quot; /&gt;
        ///	&lt;!-- This is the main ruleset. --&gt;
        ///	&lt;RuleSet&gt;
        ///		&lt;Rule foreground=&quot;Blue&quot;&gt;static:&lt;/Rule&gt;
        ///		
        ///		&lt;Rule color=&quot;Class&quot;&gt;\w+(?&amp;gt;&amp;lt;(((?!&amp;lt;|&amp;gt;)[\w,\s])*|(?&amp;lt;open&amp;gt;&amp;lt;)|(?&amp;lt;-open&amp; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string DescriptionHighlight {
            get {
                return ResourceManager.GetString("DescriptionHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 [
        ///    {
        ///        &quot;name&quot;: &quot;Select()&quot;,
        ///        &quot;actualText&quot;: &quot;Select( x =&gt; $1 )&quot;,
        ///        &quot;parent&quot;: &quot;.&quot;,
        ///        &quot;description&quot;: &quot;&quot;,
        ///        &quot;priority&quot;: 0
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;Dictionary&lt;,&gt;&quot;,
        ///        &quot;actualText&quot;: &quot;Dictionary&lt;string, object&gt;&quot;,
        ///        &quot;parent&quot;: &quot;&quot;,
        ///        &quot;description&quot;: &quot;&quot;,
        ///        &quot;priority&quot;: 0
        ///    },
        ///    {
        ///        &quot;name&quot;: &quot;if&quot;,
        ///        &quot;actualText&quot;: &quot;if ($1)\n{\n\t\n}&quot;,
        ///        &quot;parent&quot;: &quot;&quot;,
        ///        &quot;description&quot;: &quot;&quot;,
        ///        &quot;priority&quot;: 0
        ///    },
        ///    {
        ///        [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string Snippets {
            get {
                return ResourceManager.GetString("Snippets", resourceCulture);
            }
        }
    }
}
